Accesibility checks
YussufOB/My-Portfolio-Part-II pull request #6
Opened 2022-03-29 11:07 UTC by YussufOB

Hello, kindly help to review my code. The following activities were done:

1.  Includes `alt` content for all `img` elements.
2.  Includes `title` attribute to all inputs field.
3.  Provides `href` links for all anchor tags.
4.  Makes sure images are responsive.
5.  Re-access proper use of `hx` elements.
6. Update the README.md file.

2022-03-29 11:29 UTC, keroloussamy requested changes
Hi @YussufOB, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 11:29 UTC, keroloussamy commented on index.html
> +        <div class="max-card-images"><img src="./images/Snapshoot_Portfolio_1.png" alt="Portfolio Snapshot"></div>
- [ ] Kindly when I resize the page I found some text and images don't disappear or get cut off on the `works` section and on the `about` section, Kindly fix it, so when you resize you can see the whole content (text, images, buttons).

Your design
![image](https://user-images.githubusercontent.com/35535130/160600322-90b46a03-57bb-49e2-b9ab-32247281a1b1.png)

![image](https://user-images.githubusercontent.com/35535130/160600426-aca4f057-c4e7-47e8-8c89-3ca2adf14790.png)

![image](https://user-images.githubusercontent.com/35535130/160600698-93dacf98-639c-4fde-8140-37607c84bbe9.png)

2022-03-29 11:29 UTC, keroloussamy commented on index.html
>            <button type="submit" class="action-buttons">Get in touch</button>
- [ ] Kindly this button doesn't pass with the hover case, kindly make the color darker.

![image](https://user-images.githubusercontent.com/35535130/160600911-88abaf44-2674-45cc-9b40-be67e77c6d08.png)

2022-03-29 11:29 UTC, keroloussamy commented on index.html
>            <button type="button" class="action-buttons">See Project</button>
- [ ] Kindly this button doesn't pass with the hover case, kindly make the color darker to pass.

![image](https://user-images.githubusercontent.com/35535130/160601443-00ac9606-5474-4866-b7ae-567ffad74af9.png)

2022-03-30 07:49 UTC, prolajumokeoni commented
> Hello, kindly help to review my code. The following activities were done:
> 
> 1. Includes `alt` content for all `img` elements.
> 2. Includes `title` attribute to all inputs field.
> 3. Provides `href` links for all anchor tags.
> 4. Makes sure images are responsive.
> 5. Re-access proper use of `hx` elements.
> 6. Update the README.md file.
> 7. Includes changes required by the reviewer.

### OPTIONAL

- [ ] Kindly prepare a report listing all points that you have checked, and the result of your evaluation
 Your report should include:
List all points that you have checked, i.e:
- Page titles
- Image text alternatives** (<img alt="alt text">)
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

#### Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").



- [ ] Kindly add your report   to the description of your pull request, please do this because this is part of the [project requirements 
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md)

2022-03-30 08:06 UTC, prolajumokeoni approved these changes
Hi @Team,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check comment under review_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 08:32 UTC, OLIPLICHE approved these changes
Hi @YussufOB, 

Well done in working on Optional suggestions 👏👏 , your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 09:00 UTC, merged